/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesXepChuRouteImport } from './routes/games/xep-chu'
import { Route as GamesVongQuayMayManRouteImport } from './routes/games/vong-quay-may-man'
import { Route as GamesDuoiHinhBatChuRouteImport } from './routes/games/duoi-hinh-bat-chu'
import { Route as GamesAnimalChallengeRouteImport } from './routes/games/animal-challenge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesXepChuRoute = GamesXepChuRouteImport.update({
  id: '/games/xep-chu',
  path: '/games/xep-chu',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesVongQuayMayManRoute = GamesVongQuayMayManRouteImport.update({
  id: '/games/vong-quay-may-man',
  path: '/games/vong-quay-may-man',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDuoiHinhBatChuRoute = GamesDuoiHinhBatChuRouteImport.update({
  id: '/games/duoi-hinh-bat-chu',
  path: '/games/duoi-hinh-bat-chu',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAnimalChallengeRoute = GamesAnimalChallengeRouteImport.update({
  id: '/games/animal-challenge',
  path: '/games/animal-challenge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/animal-challenge': typeof GamesAnimalChallengeRoute
  '/games/duoi-hinh-bat-chu': typeof GamesDuoiHinhBatChuRoute
  '/games/vong-quay-may-man': typeof GamesVongQuayMayManRoute
  '/games/xep-chu': typeof GamesXepChuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/animal-challenge': typeof GamesAnimalChallengeRoute
  '/games/duoi-hinh-bat-chu': typeof GamesDuoiHinhBatChuRoute
  '/games/vong-quay-may-man': typeof GamesVongQuayMayManRoute
  '/games/xep-chu': typeof GamesXepChuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/animal-challenge': typeof GamesAnimalChallengeRoute
  '/games/duoi-hinh-bat-chu': typeof GamesDuoiHinhBatChuRoute
  '/games/vong-quay-may-man': typeof GamesVongQuayMayManRoute
  '/games/xep-chu': typeof GamesXepChuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/animal-challenge'
    | '/games/duoi-hinh-bat-chu'
    | '/games/vong-quay-may-man'
    | '/games/xep-chu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/animal-challenge'
    | '/games/duoi-hinh-bat-chu'
    | '/games/vong-quay-may-man'
    | '/games/xep-chu'
  id:
    | '__root__'
    | '/'
    | '/games/animal-challenge'
    | '/games/duoi-hinh-bat-chu'
    | '/games/vong-quay-may-man'
    | '/games/xep-chu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesAnimalChallengeRoute: typeof GamesAnimalChallengeRoute
  GamesDuoiHinhBatChuRoute: typeof GamesDuoiHinhBatChuRoute
  GamesVongQuayMayManRoute: typeof GamesVongQuayMayManRoute
  GamesXepChuRoute: typeof GamesXepChuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/xep-chu': {
      id: '/games/xep-chu'
      path: '/games/xep-chu'
      fullPath: '/games/xep-chu'
      preLoaderRoute: typeof GamesXepChuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/vong-quay-may-man': {
      id: '/games/vong-quay-may-man'
      path: '/games/vong-quay-may-man'
      fullPath: '/games/vong-quay-may-man'
      preLoaderRoute: typeof GamesVongQuayMayManRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/duoi-hinh-bat-chu': {
      id: '/games/duoi-hinh-bat-chu'
      path: '/games/duoi-hinh-bat-chu'
      fullPath: '/games/duoi-hinh-bat-chu'
      preLoaderRoute: typeof GamesDuoiHinhBatChuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/animal-challenge': {
      id: '/games/animal-challenge'
      path: '/games/animal-challenge'
      fullPath: '/games/animal-challenge'
      preLoaderRoute: typeof GamesAnimalChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesAnimalChallengeRoute: GamesAnimalChallengeRoute,
  GamesDuoiHinhBatChuRoute: GamesDuoiHinhBatChuRoute,
  GamesVongQuayMayManRoute: GamesVongQuayMayManRoute,
  GamesXepChuRoute: GamesXepChuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
